apiVersion: v1
kind: Service
metadata:
  name: app-{{ .Release.Name }}
  namespace: {{ .Values.nameSpace }}
#  le lb par defaut est classic lb
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: app-{{ .Release.Name }}
  type: LoadBalancer
  ports:
    - name: port1
      protocol: TCP
      port: {{ .Values.container.oracle_port }}
      targetPort: {{ .Values.container.oracle_port }}

