kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-{{ .Release.Name }}-{{ .Values.sc.zone }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: {{ .Values.sc.zone }}
  iopsPerGB: "{{ .Values.sc.iopsPerGB }}"
  fsType: ext4
reclaimPolicy: {{ .Values.sc.reclaimPolicy }} 
allowVolumeExpansion: true
